services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4294:80"
    depends_on:
      - radiolinksim
    restart: unless-stopped

  radiolinksim:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "9499:9499"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OpenElevation__BaseAddress: https://api.open-elevation.com/
    restart: unless-stopped
