services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4294:80"
    depends_on:
      - radiolinksim
    restart: unless-stopped

  radiolinksim:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "9499:9499"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OpenElevation__BaseAddress: http://open-elevation:8080/
    depends_on:
      - open-elevation
    restart: unless-stopped

  open-elevation:
    image: openelevation/open-elevation:latest
    volumes:
      - ./open-elevation-data:/code/data
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
